export const PROJECTS = {
  resumora: {
    id: 'resumora',
    name: 'Resumora',
    tagline: 'AI Resume Builder',
    color: '#c9a84c',
    domain: 'resumora.net',
    status: 'operational',
    uptime: 99.97,
    metrics: {
      frontend: { status: 'operational', label: 'Frontend Status' },
      backend: { status: 'operational', label: 'Backend Status' },
      api: { status: 'operational', label: 'API Status' },
      activeRoutes: { value: 9, label: 'Active Routes' },
      missingRoutes: { value: 0, label: 'Missing Routes' },
      brokenImports: { value: 0, label: 'Broken Imports' },
      translationEn: { value: 100, unit: '%', label: 'Translation EN' },
      translationFr: { value: 78, unit: '%', label: 'Translation FR' },
      stripe: { status: 'demo', label: 'Stripe Status' },
      auth: { status: 'configured', label: 'Auth Status' },
      responsiveness: { value: 97, unit: '%', label: 'Responsiveness' },
      mobileCompat: { value: 95, unit: '%', label: 'Mobile Compat' },
      activePlans: { value: 3, label: 'Active Plans' },
      seoScore: { value: 94, unit: '%', label: 'SEO Score' },
      googleIndex: { status: 'indexed', label: 'Google Index' },
      deployBranch: { value: 'main', label: 'Deploy Branch' },
      runtimeErrors: { value: 0, label: 'Runtime Errors' },
      lastSnapshot: { value: '2026-05-12T17:00:00Z', label: 'Last Snapshot' },
      routeConflicts: { value: 0, label: 'Route Conflicts' },
      webhookActivity: { status: 'idle', label: 'Webhook Activity' },
      deployVerified: { status: 'verified', label: 'Deploy Verified' },
    },
  },
  elegancyart: {
    id: 'elegancyart',
    name: 'ElegancyArt AI',
    tagline: 'AI E-Commerce Builder',
    color: '#8b5cf6',
    domain: 'elegancyart.com',
    status: 'operational',
    uptime: 99.89,
    metrics: {
      productSync: { status: 'synced', label: 'Product Sync' },
      supplierConn: { status: 'connected', label: 'Supplier Link' },
      aiBuilder: { status: 'operational', label: 'AI Builder' },
      deepseek: { status: 'connected', label: 'DeepSeek' },
      stripe: { status: 'active', label: 'Stripe' },
      taxAutomation: { status: 'active', label: 'Tax Automation' },
      translation: { value: 92, unit: '%', label: 'Translation' },
      socialPublish: { status: 'scheduled', label: 'Social Publish' },
      pinterestAuto: { status: 'active', label: 'Pinterest Auto' },
      instagramAuto: { status: 'active', label: 'Instagram Auto' },
      landingPages: { value: 14, label: 'Landing Pages' },
      trendEngine: { status: 'operational', label: 'Trend Engine' },
      seoPerf: { value: 91, unit: '%', label: 'SEO Score' },
      checkoutHealth: { status: 'healthy', label: 'Checkout Health' },
      conversionRate: { value: 3.4, unit: '%', label: 'Conversion Rate' },
      categoryEngine: { status: 'active', label: 'Category Engine' },
      productRotation: { status: 'active', label: 'Product Rotation' },
      automationQueues: { value: 2, label: 'Queue Depth' },
      apiRateLimits: { value: 12, unit: '%', label: 'API Rate Used' },
      deployHealth: { status: 'healthy', label: 'Deploy Health' },
      mobileRender: { value: 96, unit: '%', label: 'Mobile Render' },
      autoRecovery: { status: 'standby', label: 'Auto Recovery' },
    },
  },
  aivideo: {
    id: 'aivideo',
    name: 'AI Video Generator',
    tagline: 'Automated Video Pipeline',
    color: '#ef4444',
    domain: 'aivideo.bossmind.ai',
    status: 'operational',
    uptime: 99.72,
    metrics: {
      queueSize: { value: 3, label: 'Queue Size' },
      queueSpeed: { value: 2.1, unit: 'vid/hr', label: 'Queue Speed' },
      renderStatus: { status: 'rendering', label: 'Render Status' },
      runway: { status: 'connected', label: 'Runway' },
      luma: { status: 'connected', label: 'Luma' },
      tts: { status: 'operational', label: 'TTS Engine' },
      translationEngine: { status: 'active', label: 'Translation' },
      subtitleGen: { status: 'active', label: 'Subtitles' },
      youtubeUpload: { status: 'ready', label: 'YouTube Upload' },
      tiktokUpload: { status: 'ready', label: 'TikTok Upload' },
      failedUploads: { value: 0, label: 'Failed Uploads' },
      retryLoops: { value: 0, label: 'Retry Loops' },
      approvalFlow: { status: 'auto', label: 'Approval Flow' },
      dailyScheduled: { value: 6, label: 'Daily Scheduled' },
      supabaseLog: { status: 'logging', label: 'Supabase Logs' },
      gpuUsage: { value: 47, unit: '%', label: 'GPU Usage' },
      automationChain: { status: 'healthy', label: 'Automation Chain' },
      sceneGen: { status: 'operational', label: 'Scene Gen' },
      scriptGen: { status: 'operational', label: 'Script Gen' },
      thumbnailGen: { status: 'active', label: 'Thumbnail Gen' },
      contentCompliance: { status: 'verified', label: 'Compliance' },
      autoHealing: { status: 'standby', label: 'Auto Healing' },
    },
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok AI',
    tagline: 'Short-Form Content Engine',
    color: '#06b6d4',
    domain: 'tiktok.bossmind.ai',
    status: 'operational',
    uptime: 99.85,
    metrics: {
      shortFormGen: { status: 'active', label: 'Short-Form Gen' },
      trendTracking: { status: 'tracking', label: 'Trend Tracking' },
      viralScore: { value: 78, unit: '%', label: 'Viral Score' },
      captionAuto: { status: 'active', label: 'Caption Auto' },
      autoPublish: { status: 'scheduled', label: 'Auto Publish' },
      engagement: { value: 8.2, unit: '%', label: 'Engagement' },
      langAdaptation: { status: 'active', label: 'Language Adapt' },
      hashtagEngine: { status: 'operational', label: 'Hashtag Engine' },
      audioSync: { status: 'synced', label: 'Audio Sync' },
      regionTarget: { value: 12, label: 'Target Regions' },
      uploadPerf: { status: 'healthy', label: 'Upload Perf' },
      retryProtect: { status: 'armed', label: 'Retry Protect' },
      failedGens: { value: 1, label: 'Failed Gens' },
      aiTiming: { value: 1.3, unit: 's', label: 'AI Timing' },
      queueProcessing: { value: 5, label: 'Queue Depth' },
      socialAnalytics: { status: 'live', label: 'Social Analytics' },
      growthForecast: { value: 12, unit: '%', label: 'Growth Forecast' },
      runtimeSync: { status: 'synced', label: 'Runtime Sync' },
      autoFix: { status: 'standby', label: 'Auto Fix' },
    },
  },
  globalstock: {
    id: 'globalstock',
    name: 'Global Stock AI',
    tagline: 'Market Intelligence Platform',
    color: '#10b981',
    domain: 'stock.bossmind.ai',
    status: 'operational',
    uptime: 99.94,
    metrics: {
      marketDataSync: { status: 'live', label: 'Market Data' },
      signalEngine: { status: 'operational', label: 'Signal Engine' },
      aiAnalysis: { status: 'active', label: 'AI Analysis' },
      predictionConf: { value: 87, unit: '%', label: 'Prediction Conf' },
      apiHealth: { status: 'healthy', label: 'API Health' },
      dataLatency: { value: 42, unit: 'ms', label: 'Data Latency' },
      tradingModel: { status: 'operational', label: 'Trading Model' },
      newsEngine: { status: 'scanning', label: 'News Engine' },
      riskCalc: { status: 'active', label: 'Risk Calc' },
      portfolioEngine: { status: 'operational', label: 'Portfolio Engine' },
      strategyVerify: { status: 'verified', label: 'Strategy Verify' },
      liveUpdates: { status: 'streaming', label: 'Live Updates' },
      runtimePerf: { value: 99.2, unit: '%', label: 'Runtime Perf' },
      historyEngine: { status: 'operational', label: 'History Engine' },
      errorDetect: { value: 0, label: 'Errors Detected' },
      missingData: { value: 0, label: 'Missing Data' },
      deployHealth: { status: 'healthy', label: 'Deploy Health' },
      selfHealing: { status: 'standby', label: 'Self Healing' },
      aiCoordination: { status: 'verified', label: 'AI Coordination' },
    },
  },
};

export const GLOBAL_METRICS = {
  systemHealth: 97.8,
  automation: 95.2,
  runtimeSync: 99.1,
  autoRecovery: 98.6,
  memoryIntegrity: 99.4,
  deployVerification: 100,
  aiHarmony: 96.3,
  errorPredictionRisk: 2.1,
  activeProjects: 5,
  activeAgents: 12,
  liveDeployments: 5,
  lastValidation: '2026-05-12T17:00:00Z',
  bufferHealth: 99.7,
  queueStatus: 'processing',
  selfHealing: 'standby',
  closedLoop: 'verified',
};

export const INFRA_STATUS = {
  neonDb: { status: 'connected', latency: 8 },
  railway: { status: 'operational', deploys: 47 },
  render: { status: 'operational', deploys: 23 },
  github: { status: 'synced', commits: 189 },
  sentry: { status: 'monitoring', issues: 0 },
  n8n: { status: 'running', workflows: 14 },
};

export const ACTIVITY_LOG = [
  { time: '17:02', type: 'deploy', project: 'Resumora', message: 'Production deployment verified' },
  { time: '16:58', type: 'ai', project: 'Global Stock AI', message: 'Prediction model retrained — confidence 87%' },
  { time: '16:45', type: 'auto', project: 'AI Video Generator', message: 'Queue processed: 3 videos rendered' },
  { time: '16:30', type: 'sync', project: 'ElegancyArt AI', message: 'Product catalog synchronized — 142 products' },
  { time: '16:22', type: 'publish', project: 'TikTok AI', message: 'Auto-published 4 short-form videos' },
  { time: '16:15', type: 'heal', project: 'System', message: 'Memory integrity check passed — all projects clean' },
  { time: '16:00', type: 'scan', project: 'System', message: 'Route conflict scan completed — 0 conflicts' },
  { time: '15:45', type: 'deploy', project: 'ElegancyArt AI', message: 'Landing page auto-generated for trending product' },
  { time: '15:30', type: 'ai', project: 'Resumora', message: 'AI writing suggestions updated — 12 new templates' },
  { time: '15:15', type: 'auto', project: 'TikTok AI', message: 'Trend tracking: 3 new viral opportunities detected' },
];

export function getStatusColor(status) {
  const map = {
    operational: '#34d399', connected: '#34d399', active: '#34d399', healthy: '#34d399',
    synced: '#34d399', verified: '#34d399', indexed: '#34d399', live: '#34d399',
    streaming: '#34d399', running: '#34d399', monitoring: '#34d399', logging: '#34d399',
    tracking: '#34d399', scanning: '#34d399', armed: '#34d399',
    demo: '#f59e0b', configured: '#f59e0b', scheduled: '#f59e0b', standby: '#f59e0b',
    idle: '#f59e0b', ready: '#f59e0b', processing: '#f59e0b', auto: '#f59e0b',
    rendering: '#f59e0b',
    error: '#ef4444', down: '#ef4444', failed: '#ef4444', disconnected: '#ef4444',
  };
  return map[status] || '#6b7280';
}

export function getActivityIcon(type) {
  return { deploy: '▲', ai: '◆', auto: '⚡', sync: '↻', publish: '▶', heal: '♥', scan: '◎' }[type] || '●';
}
